version: '3.8'

services:

  db:
    image: postgres:14-alpine

    container_name: appprodutos_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: appprodutos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  db_data: